Repository spack/spack-packages, pull requests merged in 2025-06, with the labels that each got.

#172 Revert "neper: add package"
  repos/spack_repo/builtin/packages/neper/package.py
Labels: hotfix

#51 openmpi: add `fortran` variant
  repos/spack_repo/builtin/packages/openmpi/package.py
Labels: approved-by-maintainer

#247 Add actions/stale to GitHub actions
  .github/workflows/stale.yaml
Labels: ci

#62 LLVM 20 depends on Python 3.8
  repos/spack_repo/builtin/packages/llvm/package.py
Labels: waiting-on-maintainer

#322 bcl2fastq2: Fix version 2.20.0.422
  repos/spack_repo/builtin/packages/bcl2fastq2/package.py
Labels: update-package
